# Generated by Django 5.2 on 2025-05-01 14:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Bitim nomi')),
                ('description', models.TextField(verbose_name='Bitim tavsifi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Bitim summasi')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('UZS', 'UZS')], default='UZS', max_length=3, verbose_name='Valyuta')),
                ('stage', models.CharField(choices=[('LEAD', 'Lead'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('LOST', 'Lost')], default='LEAD', max_length=20, verbose_name='Bitim bosqichi')),
                ('expected_closing_date', models.DateField(verbose_name='Kutilayotgan yopilish sanasi')),
                ('closed_date', models.DateField(blank=True, null=True, verbose_name='Yopilgan sana')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to=settings.AUTH_USER_MODEL, verbose_name="Mas'ul xodim")),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='company.company', verbose_name='Kompaniya')),
            ],
            options={
                'verbose_name': 'Bitim',
                'verbose_name_plural': 'Bitimlar',
                'ordering': ['-expected_closing_date'],
            },
        ),
    ]
