# Generated by Django 5.2 on 2025-05-01 14:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('position', models.CharField(max_length=255, verbose_name='Lavozim')),
                ('email', models.EmailField(max_length=255, verbose_name='Elektron pochta')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Telefon raqami '+' bilan boshlanishi va 9-15 ta raqamdan iborat bo'lishi kerak", regex='^\\+?[0-9]{9,15}$')], verbose_name='Telefon raqami')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Asosiy kontakt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='company.company', verbose_name='Kompaniya')),
            ],
            options={
                'verbose_name': 'Kontakt',
                'verbose_name_plural': 'Kontaktlar',
                'ordering': ['-is_primary', 'last_name', 'first_name'],
                'unique_together': {('company', 'email')},
            },
        ),
    ]
