# Generated by Django 5.2 on 2025-05-01 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('contact', '0001_initial'),
        ('deal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('CALL', "Qo'ng'iroq"), ('EMAIL', 'Email'), ('MEETING', 'Uchrashuv'), ('TASK', 'Vazifa'), ('OTHER', 'Boshqa')], default='CALL', max_length=20, verbose_name='Aktivlik turi')),
                ('subject', models.CharField(max_length=255, verbose_name='Mavzu')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('due_date', models.DateTimeField(verbose_name='Bajarilish sanasi')),
                ('status', models.CharField(choices=[('PLANNED', 'Rejalashtirilgan'), ('IN_PROGRESS', 'Jarayonda'), ('COMPLETED', 'Yakunlangan'), ('CANCELED', 'Bekor qilingan')], default='PLANNED', max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name="Mas'ul xodim")),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='company.company', verbose_name='Kompaniya')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='contact.contact', verbose_name='Kontakt')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='deal.deal', verbose_name='Bitim')),
            ],
            options={
                'verbose_name': 'Aktivlik',
                'verbose_name_plural': 'Aktivliklar',
                'ordering': ['-due_date'],
                'indexes': [models.Index(fields=['company', 'status'], name='activity_ac_company_e9fd16_idx'), models.Index(fields=['due_date'], name='activity_ac_due_dat_0acc2a_idx')],
            },
        ),
    ]
