# Generated by Django 5.2 on 2025-05-01 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kompaniya nomi')),
                ('industry', models.CharField(max_length=255, verbose_name='Faoliyat sohasi')),
                ('employees_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Xodimlar soni')),
                ('annual_revenue', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Yillik daromad')),
                ('website', models.URLField(max_length=255, verbose_name='Veb-sayt')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'Kompaniya',
                'verbose_name_plural': 'Kompaniyalar',
            },
        ),
    ]
