# Generated by Django 5.2 on 2025-05-02 07:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employees_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Xodimlar soni'),
        ),
    ]
