# Generated by Django 5.2 on 2025-05-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_employees_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='annual_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Yillik daromad'),
        ),
    ]
